export const choices = [
  { id: 0, description: 'Pescoço (0)' },
  { id: 0, description: 'Região Cervical (1)' },
  { id: 0, description: 'Costas Superior (2)' },
  { id: 0, description: 'Costas Médio (3)' },
  { id: 0, description: 'Costas Inferior (4)' },
  { id: 0, description: 'Bacia (5)' },
  { id: 0, description: 'Ombro Esquerdo (6)' },
  { id: 0, description: 'Ombro Direito (7)' },
  { id: 0, description: 'Braço Esquerdo (8)' },
  { id: 0, description: 'Braço Direito (9)' },
  { id: 0, description: 'Cotovelo Esquerdo (10)' },
  { id: 0, description: 'Cotovelo Direito (11)' },
  { id: 0, description: 'Antebraço Esquerdo (12)' },
  { id: 0, description: 'Antebraço Direito (13)' },
  { id: 0, description: 'Punho Esquerdo (14)' },
  { id: 0, description: 'Punho Direito (15)' },
  { id: 0, description: 'Mão Esquerda (16)' },
  { id: 0, description: 'Mão Direita (17)' },
  { id: 0, description: 'Coxa Esquerda (18)' },
  { id: 0, description: 'Coxa Direita (19)' },
  { id: 0, description: 'Joelho Esquerdo (20)' },
  { id: 0, description: 'Joelho Direito (21)' },
  { id: 0, description: 'Perna Esquerda (22)' },
  { id: 0, description: 'Perna Direita (23)' },
  { id: 0, description: 'Tornozelo (24)' },
  { id: 0, description: 'Tornozelo (25)' },
  { id: 0, description: 'Pé (26)' },
  { id: 0, description: 'Pé (27)' },
];
